fix rmb calls timeout
threefoldtech/rmb-rs pull request #202
Opened 2024-11-28 12:16 UTC by Nabil-Salah

### Description

added exponential backoff and app exit when the listener thread is down

### Changes

`src/bins/rmb-relay.rs` file

### Related Issues

[issue#200](https://github.com/threefoldtech/rmb-rs/issues/200)

### Checklist

- [ ] Tests included
- [x] Build pass
- [ ] Documentation
- [x] Code format and docstring

2024-11-28 13:10 UTC, Nabil-Salah commented
How we tested our approch:

first we ran an rmb-relay locally on my device on a successful runs connecting to the chain 

![Screenshot from 2024-11-28 14-52-45](https://github.com/user-attachments/assets/518d8e4e-aa0e-409b-b1e8-d4258630fecb)


we started another rmb-peer connected to the local relay

![Screenshot from 2024-11-28 14-54-25](https://github.com/user-attachments/assets/e6347a50-9fad-4a90-88be-f332e0d0a6f9)

the redis database shows a successful change

![Screenshot from 2024-11-28 14-53-56](https://github.com/user-attachments/assets/3d0e7aa8-c775-45cf-adf9-c6722ca0372a)

after that I managed to cut the relay connections to the chain

![Screenshot from 2024-11-28 14-53-21](https://github.com/user-attachments/assets/02381e46-a48d-44ae-b455-d4adb5c4c0c9)

in another remote device I ran rmb-peer with different twin id and changed the relay to a local relay 

![image](https://github.com/user-attachments/assets/4eaab277-5392-471a-ba3a-6595b739fe3a)


then I released block on the connection in the previous step

![Screenshot from 2024-11-28 14-53-04](https://github.com/user-attachments/assets/71a4e045-0136-4292-a5ef-a3e6a128be4b)

and it catches the peer change in the relay

![Screenshot from 2024-11-28 14-55-00](https://github.com/user-attachments/assets/1b5b8fc8-4fa0-498d-b9c3-d1b03ddaec9e)

2024-12-04 15:23 UTC, sameh-farouk submitted a review, later dismissed
The changes introduce valuable improvements overall. However, the loop remains infinite without external exit control or mechanisms such as a termination or shutdown signal. Upon reviewing the code base, it appears that the RMB relay lacks a fully implemented graceful shutdown mechanism:

1. The main relay server loop in src/relay/mod.rs runs in an infinite loop without handling shutdown.
2. The federation worker also operates in an infinite loop without shutdown handling.
3. The event listener in this PR similarly lacks shutdown handling.

I recommend implementing proper graceful shutdown handling to ensure reliable operation. However, it would be more reasonable to address this in a separate PR.

2024-12-11 10:00 UTC, Omarabdul3ziz commented on src/bins/rmb-relay.rs
> +                        tokio::time::sleep(backoff).await;
could we make it exponential?

2024-12-11 10:59 UTC, Omarabdul3ziz requested changes
good job ya nabil, i have small comments

2024-12-11 10:59 UTC, Omarabdul3ziz commented on src/bins/rmb-relay.rs
> +                        tokio::time::sleep(backoff).await;
could we make it exponential?

2024-12-11 10:59 UTC, Omarabdul3ziz commented on src/bins/rmb-relay.rs
> +async fn app(args: Args, tx: tokio::sync::oneshot::Sender<()>) -> Result<()> {
just `oneshot::Sender<()>` right?

2024-12-11 10:59 UTC, Omarabdul3ziz commented on src/bins/rmb-relay.rs
> +                    } else {
no need for `else`? less nesting

2024-12-11 11:55 UTC, Omarabdul3ziz commented
i tired and it do retry with backoff, but can we extend the timeout? maybe 5 min

2024-12-11 12:40 UTC, Omarabdul3ziz approved these changes

2024-12-11 14:12 UTC, merged